// import './循环.js'
// import './伪数组转换为数组.js'
// import './生成新数组'
// import './查找元素'
// import './类'
// import './类如何读写属性'
// import './怎么操作一个方法'
// import './继承另一个类'
// import './处理函数参数的默认值'
// import './处理不确定参数'
// import './箭头函数'
// import './object属性简写'
// import './新的数据结构Set'
// import './新的数据结构Map'
// import './对象复制'
// import './正则'
import './ES5中字符串换行,包含变量或表达式,包含逻辑运算怎么办'